### PR TITLE
[FIX JENKINS-39689] don't embed an old version of tiger_types

### PR DESCRIPTION
**Pull request by batmat**
Which in turn is used by Stapler

### CODE REVIEW

**Comment by batmat** [comment]
Unrelated failure. Apparently CI for that plugin was broken (could not even check out the tip of the HEAD for the last failures). Just recreated the job from scratch. Apparently it's better: https://jenkins.ci.cloudbees.com/job/plugins/job/docker-plugin/1/

**Comment by batmat** [comment]
Rebased onto #458 to see if the build succeeds with that addition.

**Comment by batmat** [comment]
Great, thanks @magnayn.

I see there are quite a few commits since the last release, any plan to release a new version some day? Thanks again

**Comment by magnayn** [comment]
Yep, I'll try to roll one this week - I tend to try and soak it for a
coupla days in our production env, just to check for obvious fails :-)

**Comment by batmat** [comment]
\o/ OK, you're running the plugin in a prod env, that's really cool. Then I thoroughly agree and thanks for the feedback.

**Comment by batmat** [comment]
Hi @magnayn have you had a chance to test the SNAPSHOT? Do you plan to push some release out some time?

Thanks a lot

**Pull request merged**
