### PR TITLE
Hack around issue with Shade plugin and Maven 3.3.x

### PR DESCRIPTION
**Pull request by stephenc**
@reviewbybees

[Review on Reviewable](https://reviewable.io/reviews/jenkinsci/docker-plugin/343)

### CODE REVIEW

**Comment by KostyaSha** [comment]
:-1: will be not required because i almost resolved https://github.com/docker-java/docker-java/issues/340
Though i don't care about this plugin anymore and you can freely ignore my comments as usual

**Comment by KostyaSha** [comment]
Plus to demonstrate shading, shaded guava imports need to be replaced with normal that will be direct plugin deps. Atm plugin doing hack and using shaded guava from shaded module.

**Comment by magnayn** [comment]
Is the issue the one that I've seen (mvn 3.3.3) where sometimes the hpi doesn't build correctly (which seemed to work properly if I built only the hpi) ?

I assume it's at the expense of manually having to keep the dependencies in sync?

**Comment by stephenc** [comment]
Whether you want to bother with this is up to you. The main problem is that in Maven 3.3.x the shade plugin can not currently replace the project model with a reduced dependency model, so you need to ensure the effective transitive model is such that you don't need to produce a dependency reduced Pom.

We will likely fix this in maven once we get a chance (but given how long I'm waiting for 3.3.6 to get released, holding breath is not advised)

There are three solutions for this project:

* this PR
* add an enforcer rule to fail the building using maven [3.3.0,3.3.6) and provide an explanation why you cannot build... Be prepared to grow the range if we don't fix it in 3.3.7
* build the shaded jar in a separate reactor (which bypasses the bug completely)

I cannot see another solution

KS has muttered that he nearly has upstream producing a shaded jar in which case you could just depend on that and get back to a single module

**Comment by magnayn** [comment]
Ok. Thanks for taking the time to explain.

I think the 4th solution is 'build the shaded artifact, then build the hpi'
as 2 separate mvn invocations, which is what I tend to do in dev.

I'm minded to add for now, then once the upstream releases a shaded
artifact use that, though it shades to a different destination package. For
guava use we're currently using the target shaded package names, because
shade can't operate in the hpi itself, it seems. It'd be nice to be able to
just shade that, and not have to live with being pinned to effectively
whatever guava version docker-java declares but one thing at a time, and at
least it's a more modern version than jenkins exports.

**Comment by KostyaSha** [comment]
@stephenc may `promoteTransitiveDependencies` option be related to behaviour?

**Comment by stephenc** [comment]
@KostyaSha yes it is exactly related to this behaviour because it replaces the project model during the build and Maven 3.3.x made the project model immutable from plugins (a mistake in my view, the model should be allowed to be mutated but only for a limit set of mutations, where the transitive dependency tree of the replacement is a strict subset of the transitive dependency tree of the original model)

Thus you cannot build a reactor project where the shaded module is consumed within the same reactor using Maven 3.3.x

**Comment by stephenc** [comment]
[MNG-5899](https://issues.apache.org/jira/browse/MNG-5899)

**Pull request merged**
