### PR TITLE
JENKINS-45266: Support for setting shared memory size (--shm-size) for docker slaves

### PR DESCRIPTION
**Pull request by laenzlinger**
For our use case we would like to increase the shared memory size of the containers started by the docker-plugin. The setting is possible via the command line with the option --shm-size.

This PR allows to configure the shared memory sized in the jenkins plugin configuration (within the template config)

### CODE REVIEW

**Comment by fboudra** [comment]
it's now possible in KostyaSha/yet-another-docker-plugin 0.1.0-rc38

**Comment by laenzlinger** [comment]
We have moved to yet-another-docker-plugin

**Comment by cesarhernandezgt** [comment]
Is there any intention to merge this PR or the feature is a -1 ?

**Comment by pjdarton** [comment]
I've looked through the changes and they seem ok to me.

...however the PR would need updating as the code has moved on since this PR was authored such that it won't merge as-is.

**Comment by zucher** [comment]
Hi @laenzlinger could you retry to solve the merge request, some features in YADP like ssh login no well working.

Thank you

**Comment by pjdarton** [comment]
Rendered obsolete by #643.  All further comments should be made there.

**Pull request closed without merging**
