### PR TITLE
Add Class filter to support JEP-200 whitelist

### PR DESCRIPTION
**Pull request by bulanovk**
Add whitelisted class for JEP-200

Fix for issue https://github.com/jenkinsci/docker-plugin/issues/614

### CODE REVIEW

**Comment by sadovnikov** [comment]
Hi, Are there plans for releasing new version of the plugin with this fix? 
We use docker-plugin-1.1.3, however it's released a week too early :)

**Comment by pjdarton** [comment]
You can download the latest docker-plugin.hpi file from https://ci.jenkins.io/job/Plugins/job/docker-plugin/job/master/ and then upload that into your Jenkins via "Manage Jenkins -> Plugins -> Advanced".

**Comment by sadovnikov** [comment]
Thank you @pjdarton for your suggestion. However we are using a number of Jenkins Masters and distribute plugins' updates through Operations Center. We do need a released plugin version

**Comment by oleg-nenashev** [comment]
`com.github.dockerjava.api.command.InspectContainerResponse$Node` is not whitelisted. The serialization may fail if the field is not null

**Comment by pjdarton** [comment]
I don't think any class in the docker-plugin that needs serialization
should possess any fields from the docker-java library.
Anything in need of serialization should be extracted out of docker-java
classes.
The docker-plugin's use of docker-java should be purely "a means to an end"
rather than appearing in its API.

It's a public holiday in the UK so I don't have my computer to hand (hence
the vague reply) but I think that any fix for this should be to make all
use of docker-java be in local variables (or, if really necessary,
transient fields). Any returned data that we need to transport across
serialization should be extracted from the docker-java classes.

**Comment by ndeloof** [comment]
I fully agree none of the dockerjava classes should be part of plugin's serialization.

**Comment by oleg-nenashev** [comment]
There are also some discussion in https://issues.jenkins-ci.org/browse/JENKINS-50480

**Pull request merged**
