### PR TITLE
[FIXED JENKINS-39473] Switch to bouncycastle-api plugin for bouncycastle jars

### PR DESCRIPTION
**Pull request by stephenc**
See [JENKINS-39473](https://issues.jenkins-ci.org/browse/JENKINS-39473)

@jenkinsci/code-reviewers @reviewbybees

### CODE REVIEW

**Comment by oleg-nenashev** [comment]
LGTM 🐝

**Comment by magnayn** [comment]
Is the BC dependency in 0.16.2 breaking things currently (I.E: should a 0.16.3 be rolled )?

**Comment by stephenc** [comment]
@reviewbybees done

**Comment by stephenc** [comment]
@magnayn I suspect that people running Jenkins 1.625 - 1.647 may at random be having issues as it all depends on plugin initialization order. I do not have any specific customer issues driving this.

On Jenkins 1.648+ the bundling of bouncycastle should be idempotent (for now) as everyone is on the same version...

Rolling a 0.16.3 now will not help the people on 1.625 - 1.647... there is no fix for them other than getting a version of the docker plugin that uses the older bouncycastle. The people on 1.648+ will just have duplicate jars on the classpath (which may break things if they are running Java 9)... as such I see this as your call w.r.t. your time priorities

**Pull request merged**
