### PR TITLE
Hide null commit hash in action view

### PR DESCRIPTION
**Pull request by lanwen**
Hide empty hash on not commited container

[Review on Reviewable](https://reviewable.io/reviews/jenkinsci/docker-plugin/224)

### CODE REVIEW

**Comment by KostyaSha** [comment]
IMHO "docker" word redundant form image

**Comment by lanwen** [comment]
>Usage guidelines
>Do not modify or alter the Docker Marks; ... Use our official logo as seen above.

>Do not:
>Modify the logo in any other way than scaling it
>Use the logo without the letters 'docker'

**Comment by KostyaSha** [comment]
LOL, more docker stupideness...

**Comment by lanwen** [comment]
IMO Logo with letters a little bit prettier than without. Think it not difficult to do in way docker restrict

**Comment by KostyaSha** [comment]
According to their rules word "docker" also can't be used. Plugin has "docker" letters near logo everywhere. This absolutely redundant to have letters in two places. It prettier only because it not scaled. And btw scaling was fixed in some commits before, what plugin version do you use?

**Comment by KostyaSha** [comment]
Also please separate commits

**Comment by lanwen** [comment]
Screens with not scaled was from 0.8 (but i've seen them on 0.9 too). Ok, agree with redundant with two places "docker" word, so only commit hash hide in this pr

**Pull request merged**
