### PR TITLE
Add docker run --dns-search flag to agent template

### PR DESCRIPTION
**Pull request by kirk-fitz**
I need to be able to add --dns-search flag to agent template run command.

https://docs.docker.com/engine/network/

I have created this issue https://github.com/jenkinsci/docker-plugin/issues/1104

I believe this PR addresses this issue, but I have been unable to test this in full due to environment issues.

### Testing done

I was able to do a quick manual test and I can see the field for the --dns-search in the GUI and when I provision an agent via the template I can see the correct entry in the /etc/resolv.conf file in the container

image

image

### Submitter checklist
- [X] Make sure you are opening from a **topic/feature/bugfix branch** (right side) and not your main branch!
- [X] Ensure that the pull request title represents the desired changelog entry
- [X] Please describe what you did
- [X] Link to relevant issues in GitHub or Jira
- [ ] Link to relevant pull requests, esp. upstream and downstream changes
- [ ] Ensure you have provided tests - that demonstrates feature works or fixes the issue

### CODE REVIEW

**Comment by kirk-fitz** [comment]
Can anyone review this please?

**Comment by krisstern** [comment]
Hi @kirk-fitz, thanks for the PR! Let me review it over the next few days

**Review by krisstern — APPROVED** [review]
Thanks @kirk-fitz! This makes a lot of sense to me.

**Comment by kirk-fitz** [comment]
Thanks for reviewing @krisstern, does a maintainer need to create a release manually? Cd isnt setup on the repo?

**Comment by krisstern** [comment]
Hi @kirk-fitz, you are welcome! I think I will need to update the Jenkins version in "pom.xml" first within the next few hours before I manually release a new version of the plugin shortly afterwards. But I promise I will do it ASAP.

**Comment by kirk-fitz** [comment]
Okay, thank you

**Pull request merged**
