### PR TITLE
Add Windows containers support for JNLP slaves

### PR DESCRIPTION
**Pull request by nanori**
Add support of Windows containers as JNLP docker slaves.
Work the same way as linux part (run an init script and push config with exec command).
You can find Windows image I have used for my test [here](https://hub.docker.com/r/nanori/jenkins-windows-slave/)

Many thanks to [@Thitho007](https://github.com/Thitho007) for his precious help

Feel free to ask if you run into some issues

### CODE REVIEW

**Comment by magnayn** [comment]
LGTM - thx. I'm just going to make one change which is to default to the linux (unix) ostype if there's no other match (I.E: I suspect osType is probably solaris on smartos).

I'm happy to make that change when I merge it, or you can re-spin, whatever suits.

**Comment by nanori** [comment]
I updated code to set Linux as default Docker daemon. Moreover, I correct a mistake I've done before (forgot the "-cxe" option for bash on the start command)
Now seems to work fine on both windows and Linux

**Comment by nanori** [comment]
I'm doing some test with [@Thitho007](https://github.com/Thitho007) in a more complex environment. We run into some trouble so please wait before merging, I will do some correction during this week.

**Comment by nanori** [comment]
We solved our problems with powershell calls. Now it works as desired. To add commands to Java, I set the ```CMD_OPTS``` environment variable (for example to use a truststore, in the template's environment variable put: ```CMD_OPTS="-Djavax.net.ssl.trustStore=c:\\path\\to\\truststore"```)

**Comment by agray1017** [comment]
Has anyone successfully connected Windows Containers to their Jenkins Server? My Jenkins server successfully provisions a new container, and the logs show:
Starting connection command for f8fc8.....
Successfully executed jnlp connection for f8fc8.....
but then logs show "Waiting slave connection" until it eventually fails with a 404 Not Found:
Problem accessing /computer/docker-f8fc8b7cd9f9/logText/progressiveHtml.

Can anyone help me solve this issue?

**Comment by erik-am** [comment]
@nanori My log also shows "Waiting for slave connection". When I do `docker logs <hash>` on the provisioned on the container I find the following errors:

```
Apr 20, 2017 1:15:35 PM hudson.remoting.jnlp.Main createEngine
INFO: Setting up slave: WindowsHost-58110cb900ac
Apr 20, 2017 1:15:35 PM hudson.remoting.jnlp.Main$CuiListener <init>
INFO: Jenkins agent is running in headless mode.
Apr 20, 2017 1:15:37 PM hudson.remoting.jnlp.Main$CuiListener status
INFO: Locating server among [https://www.myjenkins.com/]
Apr 20, 2017 1:15:37 PM org.jenkinsci.remoting.engine.JnlpAgentEndpointResolver resolve
INFO: Remoting server accepts the following protocols: [JNLP4-connect, CLI2-connect, JNLP-connect, Ping, CLI-connect, JNLP2-connect]
Apr 20, 2017 1:15:37 PM hudson.remoting.jnlp.Main$CuiListener status
INFO: Agent discovery successful
  Agent address: www.myjenkins.com
  Agent port:    50000
  Identity:      40:38:c9:2c:0d:a1:c7:69:f2:e9:e4:13:14:a2:3f:6d
Apr 20, 2017 1:15:37 PM hudson.remoting.jnlp.Main$CuiListener status
INFO: Handshaking
Apr 20, 2017 1:15:37 PM hudson.remoting.jnlp.Main$CuiListener status
INFO: Connecting to www.myjenkins.com:50000
Apr 20, 2017 1:15:37 PM hudson.remoting.jnlp.Main$CuiListener status
INFO: Trying protocol: JNLP4-connect
Apr 20, 2017 1:15:38 PM hudson.remoting.jnlp.Main$CuiListener status
INFO: Remote identity confirmed: 40:38:c9:2c:0d:a1:c7:69:f2:e9:e4:13:14:a2:3f:6d
Apr 20, 2017 1:15:38 PM org.jenkinsci.remoting.protocol.impl.ConnectionHeadersFilterLayer onRecv
INFO: [JNLP4-connect connection to www.myjenkins.com/10.2.33.25:50000] Local headers refused by remote: WindowsHost-58110cb900ac is not a JNLP agent
Apr 20, 2017 1:15:38 PM hudson.remoting.jnlp.Main$CuiListener status
INFO: Protocol JNLP4-connect encountered an unexpected exception
java.util.concurrent.ExecutionException: org.jenkinsci.remoting.protocol.impl.ConnectionRefusalException: WindowsHost-58110cb900ac is not a JNLP agent
        at org.jenkinsci.remoting.util.SettableFuture.get(SettableFuture.java:223)
        at hudson.remoting.Engine.innerRun(Engine.java:385)
        at hudson.remoting.Engine.run(Engine.java:287)
Caused by: org.jenkinsci.remoting.protocol.impl.ConnectionRefusalException: WindowsHost-58110cb900ac is not a JNLP agent
```
(For privacy reasons I changed the hostname in the logs to www.myjenkins.com)

Do you have any idea what the cause could be?

**Comment by erik-am** [comment]
@nanori I had to run `jenkins.slaves.DefaultJnlpSlaveReceiver.disableStrictVerification=true` in the script console to solve the issue

**Comment by ndeloof** [comment]
obsolete. New JNLP launcher design should work out of the box for windows containers

**Comment by jlouisfoster** [comment]
Hi,

Can anyone explain exactly how to successfully connect a windows docker container via jnlp using the YADP? I can connect by manually creating the slave in my jenkins instance and passing the arguments at the command line - but want to automate provisioning with YADP.

Any help would be much appreciated ...  been at this for a day now :(

**Comment by scddev** [comment]
Hi @jlouisfoster 

basically you create a Docker image containing java (and any other tool you would need) and ensure java is on the path (I am just copying it from a samba share into my image). On your docker host you enable remote connections to the docker by tcp (c:/ProgramData/docker/config/daemon.json). Now you can configure the docker host in yad and use the image as your template.

Sample Dockerfile:
```
FROM microsoft/windowsservercore

SHELL [ "powershell" ]

ARG JAVA_VERSION=jdk1.8.0_162_x64

RUN $javaVersion = \"${env:JAVA_VERSION}\"; \
    echo \"Copying $javaVersion ...\" ; \
    $net = New-Object -ComObject WScript.Network; \
    $net.MapNetworkDrive(\"x:\", \"\\yourserver\someshare\", $false, \"youruser\", \"yourpass\"); \
    Copy-Item x:\jdks\$javaVersion -Destination C:\devtools\$javaVersion -Recurse; \
    echo \"Finished.\"

RUN $javaHome = \"C:\devtools\${env:JAVA_VERSION}\"; \
    setx PATH \"${env:PATH};$javaHome\bin\" -m; \
    setx JAVA_HOME \"$javaHome\" -m; 
```

c:/ProgramData/docker/config/daemon.json:
```
{
  "hosts": [ "tcp://0.0.0.0:2375", "npipe://" ]
}
```

Hope that helps ...

**Comment by jlouisfoster** [comment]
Hi SCDdev,

Thank you very much for responding :)

I've successfully connected my windows server 2016 dockerhost to my jenkins instance - I'm able to launch builds from my jenkins and have them pending for the created windows container.

My issue is the windows container does not connect - it will stay stuck with the following message:

"Starting connection command for 9beaae354b12c044af84b832b1130b2da1d34cdc26a3fb6a2bc34a2acac9a607"

I did not pass any arguments or parameters in the configure page for YADP for the windows image. Here is an example of my dockerfile below:

```
FROM microsoft/windowsservercore

ARG JAVA_VERSION=jdk1.8.0_131

#Enable Java#

RUN mkdir C:\Java

COPY Java_JDKJRE_1.8.0_131.zip  C:\Java
RUN powershell -command Expand-Archive C:\Java\Java_JDKJRE_1.8.0_131.zip -DestinationPath C:\Java -Force

#RUN setx /M PATH "%path%;C:\Java\jdk1.8.0_131\bin"

SHELL [ "powershell" ]

RUN $javaHome = \"C:\Java\${env:JAVA_VERSION}\"; \
    setx PATH \"${env:PATH};$javaHome\bin\" -m; \
    setx JAVA_HOME \"$javaHome\" -m; 

```

I've read in in this merge - it should work by itself, but I can't seem to get the container to connect. I can confirm that the java is in the path as I've manually launched the container, docker exec into it and tried the "java" command successfully.

**Comment by scddev** [comment]
Most of the time its a config problem if the container can not resolve the jenkins host. Please check the configuration of your jenkins if the hostname is set correctly (e.g. in case of reverse proxy or external/internal ip). Also if the Windows Server can connect to your jenkins host. Also the JNLP port has to be enabled in security configuration.

You could do a docker logs of the started container ... it should look somehow like this ...

```
~$ docker logs elated_meninsky
Found config file c:\config.ps1
###################################

Name                           Value
----                           -----
COMPUTERNAME                   B6AB85C32CF4
...
###################################
JENKINS_URL = http://yourjenkins:8080/
JENKINS_USER =
JENKINS_HOME = c:\jenkins
COMPUTER_URL = computer/windows-b6ab85c32cf4/
COMPUTER_SECRET = dad3f095a3cc0fbc5ac732019d501bd44d8b8af5cc62c544790bf02810692115
NO_CERTIFICATE_CHECK = false
JAVA_OPTS =
SLAVE_OPTS =
###################################
Invoke-WebRequest -Uri http://yourjenkins:8080//jnlpJars/slave.jar -Outfile c:\jenkins/slave.jar
java  -jar c:\jenkins/slave.jar -noReconnect  -jnlpUrl http://yourjenkins:8080//computer/windows-b6ab85c32cf4//slave-agent.jnlp -secret dad3f095a3cc0fbc5ac732019d501bd44d8b8af5cc62c544790bf02810692115
Apr 10, 2018 5:14:54 PM hudson.remoting.jnlp.Main createEngine
INFO: Setting up agent: windows-b6ab85c32cf4
Apr 10, 2018 5:14:54 PM hudson.remoting.jnlp.Main$CuiListener <init>
INFO: Jenkins agent is running in headless mode.
Apr 10, 2018 5:14:54 PM hudson.remoting.Engine startEngine
INFO: Using Remoting version: 3.19
Apr 10, 2018 5:14:54 PM hudson.remoting.Engine startEngine
WARNING: No Working Directory. Using the legacy JAR Cache location: C:\Users\ContainerAdministrator\.jenkins\cache\jars
Apr 10, 2018 5:14:55 PM hudson.remoting.jnlp.Main$CuiListener status
INFO: Locating server among [http://yourjenkins:8080/]
Apr 10, 2018 5:14:55 PM org.jenkinsci.remoting.engine.JnlpAgentEndpointResolver resolve
INFO: Remoting server accepts the following protocols: [JNLP4-connect, Ping]
Apr 10, 2018 5:14:55 PM hudson.remoting.jnlp.Main$CuiListener status
INFO: Agent discovery successful
  Agent address: yourjenkins
  Agent port:    50000
  Identity:      e5:a2:59:6e:0d:c9:fe:c0:a5:05:99:ab:57:29:87:e5
Apr 10, 2018 5:14:55 PM hudson.remoting.jnlp.Main$CuiListener status
INFO: Handshaking
Apr 10, 2018 5:14:55 PM hudson.remoting.jnlp.Main$CuiListener status
INFO: Connecting to yourjenkins:50000
Apr 10, 2018 5:14:55 PM hudson.remoting.jnlp.Main$CuiListener status
INFO: Trying protocol: JNLP4-connect
Apr 10, 2018 5:14:56 PM hudson.remoting.jnlp.Main$CuiListener status
INFO: Remote identity confirmed: e5:a2:59:6e:0d:c9:fe:c0:a5:05:99:ab:57:29:87:e5
Apr 10, 2018 5:14:57 PM hudson.remoting.jnlp.Main$CuiListener status
INFO: Connected
```

**Comment by jlouisfoster** [comment]
Just wanted to say thank you very much! The issue is now resolved - the problem was that the container could not download the slave.jar from the jenkins server. The jenkins server was ssl and the container did not have the certificate setup thus causing an SSL error.

I added the certificate in the dockerfile as follows:

```
COPY Example_Certificate.cer C:/
RUN certutil -addstore Root C:\Example_Certificate.cer
```

Again - thank you very much!

**Pull request closed without merging**
