### PR TITLE
Fix nodeName naming convention to start with cloudId

### PR DESCRIPTION
**Pull request by bulanovk**
Starting from version 1.1 node naming convention was broken, it became static "docker-" + containerId.substring(0,12) and before it was cloudId+"-" + containerId.substring(0,12).
Without name of cloud as a part of Node name it's not possible to figure out where node was provisioned.

Fix nodeName naming convention  to start with cloudId

Disable test using unix soc on Windows OS family, to be able perform build on Windows OS

fix for issue https://github.com/jenkinsci/docker-plugin/issues/576

### CODE REVIEW

**Comment by ndeloof** [comment]
changes in pom.xml and addition for JenkinsRuleWithPortBind seems unrelated to the reported issue, are they ?

**Comment by bulanovk** [comment]
Hello, agree with you. 
I moved a fix for test to separate issues: 
https://github.com/jenkinsci/docker-plugin/issues/586
https://github.com/jenkinsci/docker-plugin/issues/584

Will rebase this PR to master once Unit Test became green in master

**Comment by ndeloof** [comment]
a8cea96a751b64f4ba57d8011a2a275e3a493b65 seems irrelevant to me until we decide to require 2.86+ as minimal jenkins version for docker-plugin.

**Comment by ndeloof** [comment]
obsolete

**Pull request closed without merging**
