### PR TITLE
[JENKINS-51599] Incrementalify the Docker plugin (JEP 305)

### PR DESCRIPTION
**Pull request by batmat**
Main goal was [JENKINS-51599](https://issues.jenkins-ci.org/browse/JENKINS-51599), but I fixed some other things in the go.

There's a few different commits per change so that it is easier to grok if needed. 

Thanks!

@reviewbybees

### CODE REVIEW

**Comment by batmat** [comment]
Gentle ping @pjdarton and @ndeloof as from the recent history you seem to be the latest maintainers. Thanks!

**Comment by pjdarton** [comment]
@batmat Yup.  I've just arrived at work and seen your changes.
Always appreciate someone taking the time to tidy things up, especially when they're things that have been annoying me but I've not known how to fix them quickly ;-)

I've just been reading https://issues.jenkins-ci.org/browse/JENKINS-49866 and I would recommend that you not only look at the unix socket but go further and see if, according to the docker-commons code, there is a docker endpoint at the default location.
The help text for that field (the "Docker Host URI" field) says:
 - URI to the Docker Host you are using. May be left blank to use the Docker default (defined by DOCKER_HOST environment variable) (typically unix:///var/run/docker.sock or tcp://127.0.0.1:2376). 

i.e. The default location is not merely the unix socket, but it...
 - can be specified by the DOCKER_HOST environment variable
 - typically is the unix socket /var/run/docker.sock and/or the TCP listening socket on port 2376
 - will only be TCP if the user is foolish enough to be running Jenkins on Windows ;-)

**Comment by pjdarton** [comment]
@batmat Are your changes now ready for merge, or are there more to come?
(Looks like Nicolas is happy with the changes, and I'm also happy with them, so either of us could "press the button" whenever you're ready)

**Comment by batmat** [comment]
@pjdarton yes, it is complete for the purpose of this. So if you want and can merge, that would be great. Thanks!

**Pull request merged**
