### PR TITLE
[JENKINS-50480] JEP-200 investigation

### PR DESCRIPTION
**Pull request by jglick**
[JENKINS-50480](https://issues.jenkins-ci.org/browse/JENKINS-50480)

After reverting #619 and running tests against a JEP-200-based core, I see no test failures. So what evidence is there that a bug still exists in the `master` branch?

@reviewbybees @ndeloof @oleg-nenashev @bulanovk

### CODE REVIEW

**Comment by jglick** [comment]
I lack write access to this repo, so my `Jenkinsfile` changes are being ignored. Anyway, I ran locally against 2.107.1 and had no test failures.

**Comment by jglick** [comment]
When I ran the 1.1.2 version, I did get a _warning_ from `DockerComputerJNLPConnectorTest` (though it passed) matching the bug report. This does not happen in `master`, nor indeed in 1.1.3. So I suspect the bug is already fixed in the version on the update center.

**Comment by oleg-nenashev** [comment]
Diff between 1.1.2 and 1.1.3: https://github.com/jenkinsci/docker-plugin/compare/docker-plugin-1.1.2...docker-plugin-1.1.3

`DockerComputerJNLPConnector#createLauncher()` does not longer create anonymous class based on DelegatingComputerLauncher, so the parent class does not longer get serialized. It has been changed in https://github.com/jenkinsci/docker-plugin/commit/5a2a123cd808a9c82d154cbcc22ef906a6a97907 by @ndeloof 

I am not 100% sure this is enough to prevent all possible JEP-200 regressions in the core, but #614 is kinda fixed. I will check whether there are other JEP-200 possibilities on the surface.

**Comment by sadovnikov** [comment]
This is the exception trace we get with Jenkins 2.107.1.2 and docker-plugin 1.1.3 when the plugin tries to provision new docker agent

````
Mar 29, 2018 1:17:45 PM hudson.slaves.NodeProvisioner$2 run
WARNING: Unexpected exception encountered while provisioning agent Image of containerhub:6666/jenkins-agent:latest
java.lang.RuntimeException: java.io.IOException: java.lang.RuntimeException: Failed to serialize hudson.model.Slave#launcher for class com.nirima.jenkins.plugins.docker.DockerSlave
        at com.google.common.base.Throwables.propagate(Throwables.java:156)
        at com.nirima.jenkins.plugins.docker.DockerCloud$1.call(DockerCloud.java:304)
        at com.nirima.jenkins.plugins.docker.DockerCloud$1.call(DockerCloud.java:296)
        at jenkins.util.ContextResettingExecutorService$2.call(ContextResettingExecutorService.java:46)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.io.IOException: java.lang.RuntimeException: Failed to serialize hudson.model.Slave#launcher for class com.nirima.jenkins.plugins.docker.DockerSlave
        at hudson.XmlFile.write(XmlFile.java:200)
        at jenkins.model.Nodes.save(Nodes.java:274)
        at hudson.util.PersistedList.onModified(PersistedList.java:173)
        at hudson.util.PersistedList.replaceBy(PersistedList.java:85)
        at hudson.model.Slave.<init>(Slave.java:198)
        at hudson.slaves.AbstractCloudSlave.<init>(AbstractCloudSlave.java:51)
        at com.nirima.jenkins.plugins.docker.DockerSlave.<init>(DockerSlave.java:62)
        at com.nirima.jenkins.plugins.docker.DockerCloud.provisionFromTemplate(DockerCloud.java:406)
        at com.nirima.jenkins.plugins.docker.DockerCloud.access$000(DockerCloud.java:81)
        at com.nirima.jenkins.plugins.docker.DockerCloud$1.call(DockerCloud.java:300)
        ... 6 more
Caused by: java.lang.RuntimeException: Failed to serialize hudson.model.Slave#launcher for class com.nirima.jenkins.plugins.docker.DockerSlave
        at hudson.util.RobustReflectionConverter$2.writeField(RobustReflectionConverter.java:256)
        at hudson.util.RobustReflectionConverter$2.visit(RobustReflectionConverter.java:224)
        at com.thoughtworks.xstream.converters.reflection.PureJavaReflectionProvider.visitSerializableFields(PureJavaReflectionProvider.java:138)
        at hudson.util.RobustReflectionConverter.doMarshal(RobustReflectionConverter.java:209)
        at hudson.util.RobustReflectionConverter.marshal(RobustReflectionConverter.java:150)
        at com.thoughtworks.xstream.core.AbstractReferenceMarshaller.convert(AbstractReferenceMarshaller.java:69)
        at com.thoughtworks.xstream.core.TreeMarshaller.convertAnother(TreeMarshaller.java:58)
        at com.thoughtworks.xstream.core.TreeMarshaller.convertAnother(TreeMarshaller.java:43)
        at com.thoughtworks.xstream.core.TreeMarshaller.start(TreeMarshaller.java:82)
        at com.thoughtworks.xstream.core.AbstractTreeMarshallingStrategy.marshal(AbstractTreeMarshallingStrategy.java:37)
        at com.thoughtworks.xstream.XStream.marshal(XStream.java:1026)
        at com.thoughtworks.xstream.XStream.marshal(XStream.java:1015)
        at com.thoughtworks.xstream.XStream.toXML(XStream.java:988)
        at hudson.XmlFile.write(XmlFile.java:193)
        ... 15 more
Caused by: java.lang.RuntimeException: Failed to serialize io.jenkins.docker.connector.DockerComputerJNLPConnector$1#val$inspect for class io.jenkins.docker.connector.DockerComputerJNLPConnector$1
        at hudson.util.RobustReflectionConverter$2.writeField(RobustReflectionConverter.java:256)
        at hudson.util.RobustReflectionConverter$2.visit(RobustReflectionConverter.java:224)
        at com.thoughtworks.xstream.converters.reflection.PureJavaReflectionProvider.visitSerializableFields(PureJavaReflectionProvider.java:138)
        at hudson.util.RobustReflectionConverter.doMarshal(RobustReflectionConverter.java:209)
        at hudson.util.RobustReflectionConverter.marshal(RobustReflectionConverter.java:150)
        at com.thoughtworks.xstream.core.AbstractReferenceMarshaller.convert(AbstractReferenceMarshaller.java:69)
        at com.thoughtworks.xstream.core.TreeMarshaller.convertAnother(TreeMarshaller.java:58)
        at com.thoughtworks.xstream.core.AbstractReferenceMarshaller$1.convertAnother(AbstractReferenceMarshaller.java:84)
        at hudson.util.RobustReflectionConverter.marshallField(RobustReflectionConverter.java:265)
        at hudson.util.RobustReflectionConverter$2.writeField(RobustReflectionConverter.java:252)
        ... 28 more
Caused by: java.lang.UnsupportedOperationException: Refusing to marshal com.github.dockerjava.api.command.InspectContainerResponse for security reasons; see https://jenkins.io/redirect/class-filter/
        at hudson.util.XStream2$BlacklistedTypesConverter.marshal(XStream2.java:543)
        at com.thoughtworks.xstream.core.AbstractReferenceMarshaller.convert(AbstractReferenceMarshaller.java:69)
        at com.thoughtworks.xstream.core.TreeMarshaller.convertAnother(TreeMarshaller.java:58)
        at com.thoughtworks.xstream.core.AbstractReferenceMarshaller$1.convertAnother(AbstractReferenceMarshaller.java:84)
        at hudson.util.RobustReflectionConverter.marshallField(RobustReflectionConverter.java:265)
        at hudson.util.RobustReflectionConverter$2.writeField(RobustReflectionConverter.java:252)
        ... 37 more
````

**Comment by oleg-nenashev** [comment]
1.1.3 has no anonymous classes inside: https://github.com/jenkinsci/docker-plugin/blob/docker-plugin-1.1.3/src/main/java/io/jenkins/docker/connector/DockerComputerJNLPConnector.java

It's likely a remnant from 1.1.2. The best theory is that the plugin class still comes from 1.1.2 somehow

**Comment by sadovnikov** [comment]
Seems I have fired a false alarm. We assemble docker image with Jenkins Master and our script leaves libraries from docker-plugin `1.0.4` on the classpath.  I'll correct the script and will re-test tomorrow.

**Pull request merged**
