### PR TITLE
Add memorySwap limit configuration.

### PR DESCRIPTION
**Pull request by mpapo**
See JENKINS-30953

[Review on Reviewable](https://reviewable.io/reviews/jenkinsci/docker-plugin/340)

### CODE REVIEW

**Comment by KostyaSha** [comment]
@magnayn this change is full of bad changes. Good luck, soon you will back plugin quality to unusable state.

**Comment by magnayn** [comment]
Nope. It's following the pattern of what's already there, so is no better and no worse.

**Comment by KostyaSha** [comment]
LOL, BackwardCompatibility class exists only for migration purposes, adding new values to it shows that you don't understand this code at all. New contributors of course may not understand how to handle migration and backward compatibility, but you should understand it. Continue killing this plugin i'm going to the fork as i and many people needs stable plugin.

**Comment by magnayn** [comment]
Wow. yes. I totally see how that will make it unusable.

not.

**Comment by KostyaSha** [comment]
You can't have stability with crappy code, you already added multiple hacks that potentially bugs.
I reassigned JIRA to you, feel free to maintain plugin. You can also remove me from maintainers in pom. Now i fully understand why cloudbees making their own duplicated plugins.

**Comment by magnayn** [comment]
Somehow I just feel that's what you wanted all along.

**Comment by KostyaSha** [comment]
I wanted to make this plugin better (win provisioning stability that was implemented by your copy-paste and hacks by learning all available cloud implementations). And i wanted to have all docker related functionality in one plugin. But not after such commits and cloudbees-* hijacks.

**Comment by magnayn** [comment]
And, indeed, those changes were very worthwhile, personal abuse
notwithstanding.

**Comment by thomassuckow** [comment]
Attacking each other isn't going to make the other see your side. You are both trying to make a useful Jenkins docker plugin. The two of you just have different ideas about how to get there. If it takes a fork to achieve your goals, then so be it. That doesn't stop the possibility of sharing in the future.

https://en.wikipedia.org/wiki/Wikipedia:Assume_good_faith

**Comment by mpapo** [comment]
+1 @thomassuckow 

Moreover, I can't improve/correct this PR if you don't let me know what are my mistakes or possible improvements (I've never faced on backward compatibility problem in jenkins plugin development). 
Saying "there are bad changes" is useless for this PR and more globally doesn't serve the Jenkins community for others (new) contributors (just as personal attacks elsewhere).

**Comment by KostyaSha** [comment]
@mpapo My comment is directed only to @magnayn as we have "philosophy conflict". 

@mpapoYour PR was first of all commented by automation bot and you didn't reply to any of his comments. That's mean that this is potentially one of PRs that authors wouldn't support and fix. Plus such options was planned for fix during API sync that i periodically do. Firstly in library and then in docker-plugin. But you are lucky @magnayn likes merging and committing any changes.

**Pull request merged**
