### PR TITLE
Strategy full

### PR DESCRIPTION
**Pull request by KostyaSha**
Current version with all commits that i'm working on. #208 contains only tested portion

### CODE REVIEW

**Comment by KostyaSha** [comment]
Still testing but will be glad to get review/comments @magnayn @thomassuckow .
I will move strategy to DataBoundSetter, default should work right in most cases, so no need in having it in big constructor.
Jelly changes between two changes and it will be extremely difficult to reorder commits for me. heteroProperty now allows reordering templates that can influence for template picking for the same label that exists in multiple templates.

**Comment by KostyaSha** [comment]
It is the last big work that i have and then i will move to PR/issues fixing.

**Comment by magnayn** [comment]
Looks reasonable to me..

**Comment by KostyaSha** [comment]
Tested manually, even 2 executors with cloud strategy works fine and picks the second job from queue. 
Of course this features experimental. Will be interested in feedback later :). Merging!

**Comment by maafy6** [comment]
Will try and give this a shot next week. On vacation through the weekend.

**Pull request merged**
